service: import-service
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  profile: admin
  stage: dev
  region: eu-west-1
  environment:
    BUCKET_NAME: ${self:custom.bucketName}

plugins:
  - serverless-webpack

custom:
  bucketName: ${env:BUCKET_NAME}

package:
  individually: true

iamRoleStatements:
  - Effect: Allow
    Action: s3:ListBucket
    Resource:
      - arn:aws:s3:::${self:custom.bucketName}
  - Effect: Allow
    Action:
      - s3:*
    Resource:
      - arn:aws:s3:::${self:custom.bucketName}/*

functions:
  importProductsFile:
    handler: lambdas/endpoints/importProductsFile.handler
    events:
      - http:
          path: import
          method: GET
          parameters:
            queryStrings:
              name: true

  importFileParser:
    handler: lambdas/endpoints/importFileParser.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
