service: product-service
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  profile: pranksome-potato-admin
  stage: dev
  region: eu-west-1
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getProductsList:
    handler: lambdas/endpoints/getProductsList.handler
    events:
      - http:
          path: products
          method: GET
          cors: true

  getProductsById:
    handler: lambdas/endpoints/getProductsById.handler
    events:
      - http:
          path: products/{productId}
          method: GET
          cors: true

  createProduct:
    handler: lambdas/endpoints/createProduct.handler
    events:
      - http:
          path: products
          method: POST
          cors: true
